# Creating a logistic regression to predict absenteeism

## Importing the relevant libraries

In [19]:
import numpy as np
import pandas as pd

## Loading the Data

In [20]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## Creating the Targets

In [21]:
data_preprocessed['Absenteeism Time in Hours'].median() # anything less than or equal to 3 is moderately absent, anything more than or equal to 4 is excessively absent

3.0

In [22]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0) #if the Absenteeism Time in Hours is greater than 3, return 1, otherwise, return 0
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [23]:
data_preprocessed['Excessive Absenteeism'] = targets # making a new column with the targets variable
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [24]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [25]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis = 1)
data_with_targets #This is our new checkpoints

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                       289   33               30          0         2    1   
1                       118   50               31          0         1    0   
2                       179   38               31          0         0    0   
3                       279   39               24          0         2    0   
4                       289   33               30          0         2    1   
..                      ...  ...              ...        ...       ...  ...   
695                     179   40               22          1         2    0   
696                     225   28               24          0         1    2   
697                     330   28               25          1         0    0   
698                     235   32               25          1         0    0   
699                     291   40               25          0         1    1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [26]:
data_with_targets is data_preprocessed
# if true, the two variables refer to the same object, if false, the two variable refers to different objects

False

## Select the inputs for the regression

In [27]:
data_with_targets.shape

(700, 12)

In [28]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                       289   33               30          0         2    1   
1                       118   50               31          0         1    0   
2                       179   38               31          0         0    0   
3                       279   39               24          0         2    0   
4                       289   33               30          0         2    1   
..                      ...  ...              ...        ...       ...  ...   
695                     179   40               22          1         2    0   
696                     225   28               24          0         1    2   
697                     330   28               25          1         0    0   
698                     235   32               25          1         0    0   
699                     291   40               25          0         1    1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [29]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]

In [30]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [31]:
#from sklearn.preprocessing import StandardScaler 

#absenteeism_scaler = StandardScaler()

In [32]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler 


class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns

    def fit(self, X):
        self.scaler.fit(X[self.columns])
        return self

    def transform(self, X):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis = 1) [init_col_order]

In [33]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [34]:
#column_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
#       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

column_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [35]:
column_to_scale = [x for x in unscaled_inputs.columns.values if x not in column_to_omit]

In [36]:
absenteeism_scaler = CustomScaler(column_to_scale)

In [37]:
absenteeism_scaler.fit(unscaled_inputs).get_params()

{'columns': ['Month Value',
  'Transportation Expense',
  'Age',
  'Body Mass Index',
  'Children',
  'Pet']}

In [38]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs # all the input data has been standardized

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

          Pet  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [39]:
scaled_inputs.shape #shows that we have 700 observations and 14 features

(700, 11)

## split the data into train & test and shuffle

### Import the relevant module

In [40]:
from sklearn.model_selection import train_test_split

### Split

In [41]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 72          0         0         0         1     0.929019   
 424         1         0         0         0    -0.867426   
 96          1         0         0         0     1.228426   
 401         0         0         1         0    -1.166834   
 434         0         0         1         0    -0.568019   
 ..        ...       ...       ...       ...          ...   
 48          0         0         0         1    -0.867426   
 206         0         0         0         1    -1.466241   
 489         0         0         0         1     0.330204   
 372         0         0         0         1    -1.166834   
 278         1         0         0         0     0.629611   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 72                -0.654143  0.248310         1.002633          0 -0.919030   
 424               -1.574681  0.091435         0.297027          0 -0.919030   
 96                 1.0058

In [42]:
x_train, x_test, y_train, y_test  = train_test_split(scaled_inputs, targets, train_size=0.80, random_state=20)

In [43]:
print("Train shape:", x_train.shape, y_train.shape) #this has a vector length of 525
print("Test shape:", x_test.shape, y_test.shape) #this has a vector length of 175

#it is good to add more data onto the train variables so we can train more data

Train shape: (560, 11) (560,)
Test shape: (140, 11) (140,)


## Logistic Regression with sklearn

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the Model

In [45]:
reg = LogisticRegression()

In [46]:
reg.fit(x_train, y_train).get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [47]:
reg.score(x_train, y_train)

0.7767857142857143

### Manually check the accuracy

In [48]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [49]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [50]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [51]:
np.sum(model_outputs == y_train)

435

In [52]:
model_outputs.shape[0]

560

In [53]:
np.sum((model_outputs == y_train)/model_outputs.shape[0])

0.7767857142857144

## Finding the intercept and coefficents

In [54]:
reg.intercept_

array([-1.61205882])

In [55]:
reg.coef_

array([[ 2.77145295,  0.93066915,  3.09778986,  0.81095274,  0.00784338,
         0.62550881, -0.17366788,  0.28863529, -0.23759979,  0.35765422,
        -0.27359133]])

In [56]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [57]:
feature_name = unscaled_inputs.columns.values

In [58]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_name)

summary_table['Coefficent'] = np.transpose(reg.coef_)

summary_table

Feature Name  Coefficent
0                 Reason_1    2.771453
1                 Reason_2    0.930669
2                 Reason_3    3.097790
3                 Reason_4    0.810953
4              Month Value    0.007843
5   Transportation Expense    0.625509
6                      Age   -0.173668
7          Body Mass Index    0.288635
8                Education   -0.237600
9                 Children    0.357654
10                     Pet   -0.273591

In [59]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficent
0                Intercept   -1.612059
1                 Reason_1    2.771453
2                 Reason_2    0.930669
3                 Reason_3    3.097790
4                 Reason_4    0.810953
5              Month Value    0.007843
6   Transportation Expense    0.625509
7                      Age   -0.173668
8          Body Mass Index    0.288635
9                Education   -0.237600
10                Children    0.357654
11                     Pet   -0.273591

## Intercepting a coefficent

In [60]:
summary_table['Odds of Ratio'] = np.exp(summary_table.Coefficent)
summary_table

Feature Name  Coefficent  Odds of Ratio
0                Intercept   -1.612059       0.199477
1                 Reason_1    2.771453      15.981838
2                 Reason_2    0.930669       2.536206
3                 Reason_3    3.097790      22.148945
4                 Reason_4    0.810953       2.250051
5              Month Value    0.007843       1.007874
6   Transportation Expense    0.625509       1.869197
7                      Age   -0.173668       0.840576
8          Body Mass Index    0.288635       1.334605
9                Education   -0.237600       0.788518
10                Children    0.357654       1.429971
11                     Pet   -0.273591       0.760643

In [61]:
summary_table.sort_values('Odds of Ratio', ascending = False) #It goes from the least important to the most important 

Feature Name  Coefficent  Odds of Ratio
3                 Reason_3    3.097790      22.148945
1                 Reason_1    2.771453      15.981838
2                 Reason_2    0.930669       2.536206
4                 Reason_4    0.810953       2.250051
6   Transportation Expense    0.625509       1.869197
10                Children    0.357654       1.429971
8          Body Mass Index    0.288635       1.334605
5              Month Value    0.007843       1.007874
7                      Age   -0.173668       0.840576
9                Education   -0.237600       0.788518
11                     Pet   -0.273591       0.760643
0                Intercept   -1.612059       0.199477

## Testing the Model

In [62]:
reg.score(x_test, y_test)

0.7357142857142858

In [63]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75474481, 0.24525519],
       [0.60921599, 0.39078401],
       [0.48308941, 0.51691059],
       [0.75777492, 0.24222508],
       [0.08374243, 0.91625757],
       [0.30576765, 0.69423235],
       [0.304347  , 0.695653  ],
       [0.11593645, 0.88406355],
       [0.74028784, 0.25971216],
       [0.75604656, 0.24395344],
       [0.50623046, 0.49376954],
       [0.19494548, 0.80505452],
       [0.0622781 , 0.9377219 ],
       [0.70496055, 0.29503945],
       [0.29598613, 0.70401387],
       [0.51955449, 0.48044551],
       [0.50564345, 0.49435655],
       [0.5085783 , 0.4914217 ],
       [0.36760692, 0.63239308],
       [0.06398808, 0.93601192],
       [0.73847776, 0.26152224],
       [0.75777492, 0.24222508],
       [0.48072183, 0.51927817],
       [0.47837739, 0.52162261],
       [0.22577443, 0.77422557],
       [0.74073908, 0.25926092],
       [0.51150857, 0.48849143],
       [0.87686551, 0.12313449],
       [0.23944739, 0.76055261],
       [0.75777492, 0.24222508],
       [0.

In [65]:
predicted_proba.shape

(140, 2)

In [66]:
predicted_proba[:,1]

array([0.24525519, 0.39078401, 0.51691059, 0.24222508, 0.91625757,
       0.69423235, 0.695653  , 0.88406355, 0.25971216, 0.24395344,
       0.49376954, 0.80505452, 0.9377219 , 0.29503945, 0.70401387,
       0.48044551, 0.49435655, 0.4914217 , 0.63239308, 0.93601192,
       0.26152224, 0.24222508, 0.51927817, 0.52162261, 0.77422557,
       0.25926092, 0.48849143, 0.12313449, 0.76055261, 0.24222508,
       0.38855   , 0.71169728, 0.69771064, 0.49494357, 0.24222508,
       0.59774891, 0.26016392, 0.78069438, 0.43997582, 0.60636346,
       0.24179429, 0.49700761, 0.25835995, 0.40639195, 0.8073977 ,
       0.59952536, 0.71883372, 0.24308822, 0.24666618, 0.24136403,
       0.5017043 , 0.29321567, 0.69423235, 0.24449079, 0.82001991,
       0.39190275, 0.90627341, 0.26421695, 0.32126132, 0.32177361,
       0.70512513, 0.69572579, 0.26558883, 0.77627144, 0.24519155,
       0.24482075, 0.07526493, 0.26061618, 0.76236107, 0.29699697,
       0.25746103, 0.31516581, 0.88396409, 0.43881888, 0.59548

## Saving the Model

In [68]:
import pickle

In [69]:
with open('model', 'wb') as file:  #model is the file name and wb stands for write bytes
    pickle.dump(reg, file) #dump the info into the file
    # this is seperating the model from the training data for good

In [72]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)